//BUDGET OPTIONS ARRAY
const budgetOptions = [
    {
        level: "D",
        description: "Callow Hero, Freshman",
        budget: 10
    },
    {
        level: "C",
        description: "Adept Hero, Sophomore",
        budget: 20
    },
    {
        level: "B",
        description: "Expert Hero, Seasoned",
        budget: 30
    },
    {
        level: "A",
        description: "Renowned Hero, Veteran",
        budget: 40
    },
    {
        level: "S",
        description: "Epic Hero, Legend",
        budget: 50
    },
];

//SCORE ARRAY
const scoreOptions = [
    {
        description: "One",
        score: 1,
    },
    {
        description: "Two",
        score: 2,
    },
    {
        description: "Three",
        score: 3,
    },
];

//OUTCOME SCORES ARRAY
const outcomeScore = "Outcome: 1 to 3 = Good, lasts 3 rounds. <br> 4 or more = Awesome, lasts until the encounter ends.</b>";

//UPGRADE ARRAY
const upgrades = [
    {
        grade: 'D', ref: 1, spr: 1, wits: 1
    },
    {
        grade: 'C', ref: 1, spr: 1, wits: 1
    },
    {
        grade: 'B', ref: 2, spr: 2, wits: 2
    },
    {
        grade: 'A', ref: 2, spr: 2, wits: 2
    },
    {
        grade: 'S', ref: 3, spr: 3, wits: 3
    },
];

//ABILITY TIER ARRAY
const abilityTier = [
    { tier: 0, grade: "Grade", pool: "Pool", cost: "Cost" },
    { tier: 1, grade: 'D', pool: 1, cost: 1 },
    { tier: 1, grade: 'C', pool: 2, cost: 2 },
    { tier: 1, grade: 'B', pool: 3, cost: 3 },
    { tier: 1, grade: 'A', pool: 4, cost: 4 },
    { tier: 1, grade: 'S', pool: 5, cost: 5 },
    { tier: 2, grade: 'D', pool: 1, cost: 2 },
    { tier: 2, grade: 'C', pool: 2, cost: 4 },
    { tier: 2, grade: 'B', pool: 3, cost: 6 },
    { tier: 2, grade: 'A', pool: 4, cost: 8 },
    { tier: 2, grade: 'S', pool: 5, cost: 10 },
    { tier: 3, grade: 'D', pool: 1, cost: 3 },
    { tier: 3, grade: 'C', pool: 2, cost: 6 },
    { tier: 3, grade: 'B', pool: 3, cost: 9 },
    { tier: 3, grade: 'A', pool: 4, cost: 12 },
    { tier: 3, grade: 'S', pool: 5, cost: 15 }
];

//AREA SIZE ARRAY
const areaSize = [
    {
        grade: "D", size: "A small bedroom"
    },
    {
        grade: "C", size: "The Loop Chicago"
    },
    {
        grade: "B", size: "New York City"
    },
    {
        grade: "A", size: "Illinois State"
    },
    {
        grade: "S", size: "Antarctica"
    },
];

//ABILITY LIST ARRAY
const abilityList = [
    {
        name: "ADHESION",
        power: false,
        description: "The ability to adhere to and move a surface regardless of gravity. No stunt roll needed, simply declare the action to crawl or walk along a plane heedless of gravity. Stick: Subtract your adhesion pool from the outcome when the Tags Push or Pull are used against you.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "AGILITY",
        power: false,
        description: "This ability represents extraordinary agility, balance and manual dexterity. Add the Agility pool to Physical stunts such as acrobatics, aiming, climbing, piloting, hand eye coordination, etc.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Action", "Reflex"],
        table: [],
        tags: ["Counter", "Reflect"],
    },
    {
        name: "AURA",
        power: true,
        description: "You possess an aura that changes the conditions of the area you occupy. Choose what your Aura could imposes, be it zero gravity, icy surfaces, an earthquake, psychic waves, torrential rain, etc. Add Aura to a Will stunt vs a difficulty set by the Narrator. The outcome determines the duration of the Aura. For others the Aura pool adds to the difficulty of all stunts performed within. The higher the grade the more extreme the changes to the space of influence. Epicenter: The Aura is always centered around the bearer making it harder to do them harm. Subtract the Aura pool from the outcome of physical stunts made against your Reflex. The pool is the number of times Epicenter can be used during an encounter. Only one instance of this ability can be in play at a time.",
        damage: [],
        outcome: outcomeScore,
        tier: 3,
        upgrades: ["Reflex"],
        table: [
            {
                grade: "D", size: "A small bedroom"
            },
            {
                grade: "C", size: "The Loop Chicago"
            },
            {
                grade: "B", size: "New York City"
            },
            {
                grade: "A", size: "Illinois State"
            },
            {
                grade: "S", size: "Antarctica"
            }
        ],
        tags: ["Continue", "Damage", "Damage Type", "Pierce"],
    },
    {
        name: "BIND",
        power: true,
        description: "Shoot out a binding that immobilizes a target at range. Add the Bind pool to a Physical stunt vs. the target's Reflex. On a hit the captive cannot move and their reflex drops to zero. Escape requires the captive to roll a Physical stunt vs the Bind pool.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: ["Area of Effect", "Contagion", "Continue", "Counter", "Damage", "Damage Type", "On Contact", "Pierce", "Pull", "Reflect"],
    },
    {
        name: "BURROWING",
        power: false,
        description: "You can burrow through the ground or big solid objects. You can do so at a rate akin to having the Speed ability at your Burrowing grade. Whenever you burrow you can decide whether or not to leave a tunnel in your wake. Entomb: Add the Burrowing pool to a Physical stunt vs. a target's Wits, on a hit the target cannot move and their reflex drops to zero as they've been pulled into the ground. Escape requires them to roll a Physical stunt vs the Entomb outcome.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Wits"],
        table: [],
        tags: [],
    },
    {
        name: "BRAINS",
        power: false,
        description: "You possess a high IQ, quick thinking and vast memory. Add the Brain pool to Intelligence stunts that test intellect, memory recall and complex problem solving.",
        damage: [],
        outcome: "",
        tier: 1,
        upgrades: ["Action"],
        table: [],
        tags: [],
    },
    {
        name: "CHARM",
        power: false,
        description: "You are charismatic, others find your magnetic personality inspiring and persuasive. Add the Charm pool to a Will stunt vs the target's Spirit. While under your Charm your ability pool is added to their stunt rolls when their purpose suits your stated interests.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: ["Action"],
        table: [],
        tags: [],
    },
    {
        name: "COMPANION",
        power: true,
        description: "This ability represents an autnomous entity over which you have great influence. This companion is driven to help you achieve your interests. Companions have an INT, WILL and PHY, choose which is 1, which is 2 and which is 3. The Companion's Action, Wits, Spirit and Reflex are determined as normal. Companions are considered to have the ability Endurance at a grade equal to the Companion ability. So a grade B Companion has grade B Endurance. If your Companion has an ability that also grants Endurance use the highest pool and health bar. The Companion grade pool is used as points that are slotted into abilities the Companion possesses. Each point slotted into a Companion ability raises that ability's grade by one.",
        damage: [],
        outcome: "",
        tier: 3,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "COMPUTING",
        power: false,
        description: "This ability represents the advanced operation of computers. Add the Computing pool to Intelligence stunts like writing applications, data research, securing networks, hacking systems, etc. ",
        damage: [],
        outcome: "",
        tier: 1,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "COPY",
        power: true,
        description: "The power to copy abilities you witness while in the presence of the owner. Roll Intelligence plus Copy vs the target ability’s pool. The outcome determines when the copied ability expires. Copied abilities are the same grade as the original but cannot exceed your copy grade. The number of abilities you can copy at one time is limited by your copy grade pool.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: [],
        table: [],
        tags: ["On Contact"],
    },
    {
        name: "DANGER SENSE",
        power: true,
        description: "A talent for reflexively avoiding concealed or sudden attacks. During an encounter subtract your Danger Sense pool from the outcome of an attack targeting your Wits. Covers, sneak attacks, ambushes, traps, falling debris, etc. The Danger Sense pool is the number of times this can be done in an encounter.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: ["Wits"],
        table: [],
        tags: [],
    },
    {
        name: "DEFTNESS",
        power: false,
        description: "Great manual dexterity when performing fine manipulation. Add the Deftness pool to Physical stunts vs difficulty or Wits. Deftness applies to stunts like creating forgeries, demolition, safecracking, stitching wounds, picking pockets, etc. ",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "DEPOWER",
        power: true,
        description: "The power to temporarily remove abilities from others. When you depower another they lose an ability of your choice. Roll your Intelligence plus the Depower pool vs the target ability's pool. The outcome determines how long before use of the stripped ability returns. Your Depower pool is the number of abilities you can depower during an encounter.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "DISGUISE",
        power: false,
        description: "Alter your appearance, movements and voice to create the facade of being another person or thing. Add the Disguise pool to Intelligence stunts vs. difficulty or Wits.The outcome is the difficulty for any attempt to see through the disguise.",
        damage: [],
        outcome: "",
        tier: 1,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "DRAIN",
        power: true,
        description: "Through physical contact you can drain health from a target to replenish your own. Add the Drain pool to a Physical stunt vs. the target's Reflex. The outcome is the amount of health you take from the target and use to replenish your own.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "DRIVE",
        power: false,
        description: "Drive represents extraordinary willpower. Add the Drive pool to Will stunts that test will power, psychic power or magic skill. Focus: You can concentrate your will upon accomplishing a single task. For every turn you pass, performing no stunt, you can reduce the difficulty or defense you’re rolling against by 1. This amount cannot exceed your drive grade. Losing enough health to reduce you to serious before performing the stunt cancels focus. You can control the movement of vehicles, animals, or objects. Add the Drive pool to a Physical stunt vs. difficulty or Wits. Drive applies to stunts like piloting, steering, or operating machinery. ",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Spirit"],
        table: [],
        tags: [],
    },
    {
        name: "ELASTICITY",
        power: false,
        description: "Stretch and twist your limbs and body as if you were made of elastic. You can interact with distant items and attack targets at range. Also, add your elasticity pool to climb and acrobatic stunts. Rubber: Subtract the Elasticity pool from the outcome of physical stunts made against your Reflex. The pool is the number of times you can do this during an encounter. Envelope: You can wrap your body around captives. The Elasticity pool is the difficulty to escape, you lose health equal to the outcome of their escape stunt. You can stretch and contract your body to move or attack. Add the Elasticity pool to a Physical stunt vs. difficulty or Wits. Elasticity applies to stunts like stretching, contracting, or leaping. ",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Action", "Reflex"],
        table: [],
        tags: ["Area of Effect", "Chain", "Counter", "Homing", "Pull", "Push", "Reflect"],
    },
    {
        name: "EMPATHY",
        power: true,
        description: "The ability to experience the feelings of another. Roll Will plus Empathy vs Spirit, the outcome determines how long you’re empathic. Add the outcome to your Reflex when the subject of your empathy attempts a melee or ranged attack against you.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "EMPOWER",
        power: true,
        description: "The power to grant others temporary abilities. Theme: When you purchase this ability you must describe its source. eg. inspirational oration, biokinesis, spellcasting, etc. When you empower another they receive an ability of your choice at the grade you choose. The highest grade you can grant equals your Empower grade. Roll your Intelligence plus Empower pool vs the pool of the recipient's highest ability grade. The outcome determines how long the granted abilities last. Your Empower pool is the number of abilities you can grant during an encounter. You cannot grant the Empower ability.",
        damage: [],
        outcome: outcomeScore,
        tier: 3,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "ENDURANCE",
        power: false,
        description: "You possess extraordinary stamina and resilience. Add endurance to Physical stunts that challenge stamina or constitution. Your endurance health bar replaces the default health bar. The power to temporarily enhance abilities in others. Theme: When you purchase this ability you must describe its source. eg. inspirational oration, biokinesis, spellcasting, etc. When you empower another they receive an ability of your choice at the grade you choose. The highest grade you can grant equals your Empower grade. Roll your Intelligence plus Empower pool vs the pool of the recipient's highest ability grade. The outcome determines how long the granted abilities last. Your Empower pool is the number of abilities you can grant during an encounter. You cannot grant the Empower ability.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [
            { grade: "D", good: "x3", ok: "x2", serious: "x2", critical: "x2", ko: "x1" },
            { grade: "C", good: "x4", ok: "x2", serious: "x2", critical: "x2", ko: "x2" },
            { grade: "B", good: "x4", ok: "x3", serious: "x3", critical: "x2", ko: "x2" },
            { grade: "A", good: "x4", ok: "x3", serious: "x3", critical: "x3", ko: "x3" },
            { grade: "S", good: "x5", ok: "x5", serious: "x4", critical: "x3", ko: "x3" }
        ],
        tags: [],
    },
    {
        name: "EVADE",
        power: false,
        description: "The ability to parry or dodge harm. Evade: Subtract your Evade pool from the outcome of an attack targeting your reflex. Your Evade pool is the number of times you can use Evade during an encounter. The power to temporarily enhance abilities in others. Theme: When you purchase this ability you must describe its source. eg. inspirational oration, biokinesis, spellcasting, etc. When you empower another they receive an ability of your choice at the grade you choose. The highest grade you can grant equals your Empower grade. Roll your Intelligence plus Empower pool vs the pool of the recipient's highest ability grade. The outcome determines how long the granted abilities last. Your Empower pool is the number of abilities you can grant during an encounter. You cannot grant the Empower ability.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Reflex"],
        table: [],
        tags: ["Counter", "Reflect"],
    },
    {
        name: "EXTRA LIMBS",
        power: false,
        description: "You have additional limbs. Add your Extra Limb pool to Physical stunts that involve complex maneuvering. For instance grappling, climbing, swimming or melee weapons. Extra: You can perform additional stunts during your action. Your grade determines how many extra stunts you get, extra stunts must be physical. The Extra Limb pool is the number of times Extra can be used during an encounter.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Reflex"],
        table: [
            { grade: "D", extraStunts: 1 },
            { grade: "C", extraStunts: 1 },
            { grade: "B", extraStunts: 2 },
            { grade: "A", extraStunts: 2 },
            { grade: "S", extraStunts: 3 }
        ],
        tags: ["Area of Effect", "Chain", "Counter", "Pull", "Push", "Reflect"],
    },
    {
        name: "FIELD",
        power: false,
        description: "You can sheath yourself in a protective field. Subtract damage affected by the field from its health bar instead of your own. If your Field doesn't affect an incoming damage type it is instead subtracted from your health bar. Damage types not covered by the field pass simply through. Choose the damage type your field affects; cold, energy, heat, mystic, physical, psychic, radiation, suffocation and toxin. Inform the Narrator when you raise your Field, in game this is a simple task. The last box you marked off of your field's health bar represents its current condition. Once you cross out the last box labeled  \"down\" your field is down. At the end of each round fields recover one health box. If you drop a damaged field during your action you may reraise the field on a subsequent action at its full health.",
        damage: [
            { name: "COLD", abbreviation: "(Col)" },
            { name: "ENERGY", abbreviation: "(Ene)" },
            { name: "HEAT", abbreviation: "(Hea)" },
            { name: "MYSTIC", abbreviation: "(Mys)" },
            { name: "PHYSICAL", abbreviation: "(Phy)" },
            { name: "PSYCHIC", abbreviation: "(Psy)" },
            { name: "RADIATION", abbreviation: "(Rad)" },
            { name: "SUFFOCATION", abbreviation: "(Suf)" },
            { name: "TOXIN", abbreviation: "(Tox)" },
        ],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [
            { grade: "D", good: "x3", ok: "x2", serious: "x2", critical: "x2", ko: "x1" },
            { grade: "C", good: "x4", ok: "x2", serious: "x2", critical: "x2", ko: "x2" },
            { grade: "B", good: "x4", ok: "x3", serious: "x3", critical: "x2", ko: "x2" },
            { grade: "A", good: "x4", ok: "x3", serious: "x3", critical: "x3", ko: "x3" },
            { grade: "S", good: "x5", ok: "x5", serious: "x4", critical: "x3", ko: "x3" }
        ],
        tags: ["Absorb", "Affect Type", "Reflect"],
    },
    {
        name: "FIGHT",
        power: false,
        description: "Fight represents skill or talent in unarmed combat. Add the Fight pool to Physical stunts vs the target's Reflex. When the stunt represents an unarmed attack the outcome is the damage dealt. Subtract the outcome from the target's health. The default damage type is Physical. But when Fight is used in conjunction with a Melee Attack default to its damage type. E.g. studded gloves or metal toed boots.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Reflex"],
        table: [],
        tags: ["Chain", "Counter", "Extra Attack", "Push"],
    },
    {
        name: "FLIGHT",
        power: false,
        description: "You can fly. Add the Flight pool to a Physical stunt vs. difficulty or Wits. Flight applies to stunts like flying, gliding, or hovering. ",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Reflex"],
        table: [],
        tags: [],
    },
    {
        name: "GESTALT",
        power: false,
        description: "The ability to merge your mind and body with others becoming a single more powerful being. The Gestalt possesses all of the abilities of its collective at the same grades. The total number of partners you may merge with at one time is determined by your Gestalt grade. If none of the collective possess Might or Endurance the Gestalt gains those abilities at the same grade as the source Gestalt ability. If the collective Might or Endurance is lower than the Gestalt ability the Gestalt gains the ability at the Gestalt grade. Gestalts have an INT 1, WILL 2, PHY 3 and its Action, Wits, Spirit and Reflex are determined using the upgrades from the abilities of its collective. Once the Gestalt merges, roll its Will plus Focus or Resolve if available vs the highest Spirit among the Collective. The outcome determines how long before the Gestalt separates. All participants must consent to merger. Merging into a Gestalt or splitting back into individuals is a simple action. A Gestalt that has separated on its turn cannot merge again on the next turn. It must wait until the turn after next to reconstitute. At any time a member of the Gestalt can separate from the collective entity. This will cause the Gestalt to separate back into its individual members.",
        damage: [],
        outcome: outcomeScore,
        tier: 3,
        upgrades: [],
        table: [{ grade: "D", partners: 1 }, { grade: "C", partners: 1 }, { grade: "B", partners: 2 }, { grade: "A", partners: 3 }, { grade: "S", partners: 4 }],
        tags: [],
    },
    {
        name: "GROWTH",
        power: false,
        description: "You possess the power to grow to gigantic proportions. While in use Growth functions like the abilities Might and Endurance at the same grade as Growth. Big Target: Giants have a normal Reflex as well as a one vs. normal sized attackers. While in use Growth reduces your Reflex vs normal sized attackers or smaller. See Reflex below. You can temporarily increase your size. Add the Growth pool to a Physical stunt vs. difficulty or Wits. Growth applies to stunts like growing larger, increasing strength, or enhancing durability. Note: When player characters are playing a Gestalt they must agree unanimously on each action the Gestalt takes. Otherwise the Gestalt loses that turn to the chaotic den of indecision overriding its mind.",
        damage: [],
        outcome: "",
        tier: 3,
        upgrades: [],
        table: [
            { grade: "D", height: "50'", weight: "1500 lbs", reflex: "-1" },
            { grade: "C", height: "100'", weight: "10 tns", reflex: "-1" },
            { grade: "B", height: "500'", weight: "700 tns", reflex: "-2" },
            { grade: "A", height: "1000'", weight: "2 mil tns", reflex: "-2" },
            { grade: "S", height: "2500'", weight: "5 mil tns", reflex: "-3" },
        ],
        tags: [],
    },
    {
        name: "HEAL OTHERS",
        power: true,
        description: "The power to heal others. You must be within arms reach of the patient. Roll your Heal Others pool plus your Intelligence vs the patient's degree of injury; Good = 0, Serious = 1, Critical = 2 and KO = 3, your pool cannot be reduced below 1. The outcome is the number of health boxes the patient regains.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "HEAL SELF",
        power: true,
        description: "You heal faster than normal. At the end of the round roll your Heal Self pool plus your Physical vs your degree of injury; Good = 0, Serious = 1, Critical = 2 and KO = 3, your pool cannot be reduced below 1. The outcome is the number of health boxes you regain.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "IMAMATERIAL",
        power: false,
        description: "You can become immaterial to solid matter. Becoming immaterial is a simple task. While immaterial you can pass through solid material and ignore all physical damage. Also your Physical stunts have no effect on others or the material world. Ghost: With concentration you can become partially material. In this state you can perform Physical stunts while remaining immune to physical harm. The pool is the number of times you can use Ghost during an encounter.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "IMPAIR MOVE",
        power: true,
        description: "Cast a substance or energy that hinders a target's movement. Add the Impair Move pool to a Physical stunt vs the target's Reflex at range. If successful the target's Physical stunt pools and Reflex are reduced by the Impair Move pool. Compare the outcome to the chart below to determine the duration of the impairment.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: [],
        table: [],
        tags: ["Area of Effect", "Contagion", "On Contact", "Pull", "Push"],
    },
    {
        name: "IMPAIR SENSE",
        power: true,
        description: "Emit a power that temporarily impairs a target's senses. Add the Impair Sense pool to an Intelligence stunt against a target's Wits at a range. Each grade allows you to impair an additional sense\u2026 Sight, Hearing, Smell, Touch and Taste. If the stunt succeeds the target's Intelligence stunt pools and Wits are reduced by the Impair Sense pool. Compare the outcome to the chart below to determine the duration of the impairment.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: [],
        table: [],
        tags: ["Area of Effect", "Contagion", "On Contact", "Pull", "Push"],
    },
    {
        name: "IMPAIR THOUGHT",
        power: true,
        description: "Emit a power that temporarily sedates a target's mind. Add the Impair Thought pool to a Will stunt against a target's Spirit at a range. If the stunt succeeds the target's Will stunt pools and Spirit are reduced by the Impair Thought pool. Compare the outcome to the chart below to determine the duration of the impairment.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "IMPERVIOUS",
        power: false,
        description: "You are impervious to a specific type of damage. You can ignore the outcome of a specific damage type. Choose a damage type for each grade of Impervious\u2026 cold, energy, heat, mystic, physical, psychic, radiation, suffocation and toxin.",
        damage: [
            { name: "COLD", abbreviation: "(Col)" },
            { name: "ENERGY", abbreviation: "(Ene)" },
            { name: "HEAT", abbreviation: "(Hea)" },
            { name: "MYSTIC", abbreviation: "(Mys)" },
            { name: "PHYSICAL", abbreviation: "(Phy)" },
            { name: "PSYCHIC", abbreviation: "(Psy)" },
            { name: "RADIATION", abbreviation: "(Rad)" },
            { name: "SUFFOCATION", abbreviation: "(Suf)" },
            { name: "TOXIN", abbreviation: "(Tox)" },
        ],
        outcome: "",
        tier: 3,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "INDUCE FEAR",
        power: true,
        description: "The psychic power to induce fear in others. Add the Induce Fear pool to a Will stunt vs the target's spirit. The target is unable to attack the inducer and must get as far from them as possible. The outcome determines how long the target is terrified.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "INSPECT",
        power: false,
        description: "You're able to investigate a scene and pick up hidden details and clues. Add the Inspect pool to an Intelligence stunt vs the narrator's difficulty.",
        damage: [],
        outcome: "",
        tier: 1,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "INTIMIDATE",
        power: false,
        description: "The ability to threaten, strong arm or dissuade others. Add the Intimidate pool to a Will stunt vs the target's Spirit. Their next stunt pool is reduced by your Intimidate pool.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "KNOW",
        power: false,
        description: "You know the faces and places that comprise a specific library of information. Be it the criminal underworld, local law enforcement, the club scene, etc. Confer with the Narrator to make up a subject that fits their campaign. Add the Know pool to an Intelligence stunt vs the narrator's difficulty.",
        damage: [],
        outcome: "",
        tier: 1,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "LEAP",
        power: true,
        description: "You can leap great distances in a single bound. Add the Leap pool to Physical stunts related to acrobatics, climbing, gymnastics and of course leaping.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Action", "Reflex"],
        table: [],
        tags: [],
    },
    {
        name: "MAGIC",
        power: false,
        description: "Magic represents occult knowledge and skilled spellcasting. Add the Magic pool to Intelligence stunts to decipher or create occult text. Spell Caster: Add the Magic pool to Will stunts alongside abilities that represent spells being cast. I.e. You could add Magic to a Will stunt pool along with the ability Ranged Attack to represent a fireball spell.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Spirit"],
        table: [],
        tags: ["Chain"],
    },
    {
        name: "MELEE ATTACK",
        power: true,
        description: "This ability represents a special unarmed attack, or melee weapon e.g. a jump kick, panther claws, warhammer, etc. To use Melee Attack perform a Physical stunt. If successful, add the ability bonus to the outcome when determining damage. Subtract the total outcome from the target's health. Choose which type of damage is inflicted\u2026 heat, cold, energy, mystic, physical, psychic, radiation or toxin.",
        damage: [
            { name: "COLD", abbreviation: "(Col)" },
            { name: "ENERGY", abbreviation: "(Ene)" },
            { name: "HEAT", abbreviation: "(Hea)" },
            { name: "MYSTIC", abbreviation: "(Mys)" },
            { name: "PHYSICAL", abbreviation: "(Phy)" },
            { name: "PSYCHIC", abbreviation: "(Psy)" },
            { name: "RADIATION", abbreviation: "(Rad)" },
            { name: "SUFFOCATION", abbreviation: "(Suf)" },
            { name: "TOXIN", abbreviation: "(Tox)" },
        ],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: ["Area of Effect", "Bypass", "Contagion", "Continue", "Damage Type", "Extra Attack", "Feed", "On Contact", "Pierce", "Push", "Reflect"],
    },
    {
        name: "MELEE SKILL",
        power: false,
        description: "Melee Skill represents skilled use of melee weapons or talent at wielding improvised weapons. Add the Melee Skill pool to a Physical stunt vs the target's Reflex.",
        damage: [],
        outcome: "",
        tier: 1,
        upgrades: [],
        table: [],
        tags: ["Chain", "Counter", "Extra Attack", "Feed", "Reflect"],
    },
    {
        name: "MENTAL ILLUSION",
        power: true,
        description: "The ability to psychically alter one's perception of reality. Add the Mental Illusion pool to a Will stunt vs. the target's Spirit. The outcome determines how long the projection lasts. The illusionist describes the illusion the subject experiences. The projection is perceived as completely real, leaving the target deaf and blind to reality.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: [],
        table: [],
        tags: ["Contagion", "On Contact"],
    },
    {
        name: "MIGHT",
        power: false,
        description: "You possess extraordinary physical strength. Add the Might pool to Physical stunts related to strength, swimming, climbing, unarmed fighting and melee weapon use.",
        damage: [],
        outcome: "",
        tier: 1,
        upgrades: [],
        table: [],
        tags: ["Area of Effect", "Counter", "Reflect"],
    },
    {
        name: "MIND CONTROL",
        power: true,
        description: "The psychic power to take control of another's mind. Add Mind Control to a Will stunt vs the subject's Spirit. The outcome determines how long control lasts. The subject will carry out your command on their action. A command to harm oneself will be followed. However a command that will result in the subject's death will be ignored.",
        damage: [],
        outcome: outcomeScore,
        tier: 3,
        upgrades: ["Spirit"],
        table: [],
        tags: ["Contagion", "On Contact"],
    },
    {
        name: "MULTI-ABILITY",
        power: true,
        description: "A power or item that can produce the effects of multiple abilities. Theme: When you purchase this ability you must describe its source. eg. a magic ring, utility belt, cybernetic arm, etc. The multi-ability grade can be changed into a different ability at the same grade or split among multiple abilities and Tags. Abilities produced with multi-ability function as those abilities. The Multi-Ability grade pool is used as points that are slotted into the abilities you choose. Each point slotted into an ability raises its grade by one. Each Tag you apply to a slotted ability costs a pool point. Switching between abilities and Tags counts as a simple task. Example: You have TRANSMUTATION Multi-ability A 4. You change a crook's clothes into glue. So you slot 3 of your points into the ability Bind at grade B and give it the tag contagion. That’s 3 points to get Bind at grade B and 1 point to add the tag contagion.",
        damage: [],
        outcome: "",
        tier: 3,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "MULTIPLY",
        power: false,
        description: "You can produce independently thinking and acting duplicates of yourself. Your duplicates possess all of your stats and abilities excluding Multiply. Duplicates can be produced or aborted as a simple task. All of your Duplicates share a single Duplicates health bar. Once the Duplicates health bar is depleted you're out of Dupes for this encounter. All Hands: Add Multiply to Physical stunts and unarmed attacks, your pool is the number of times this can be done in an encounter. Explode: Perform a burst of unarmed attacks on multiple targets in one action. Explode by adding Multiply to your stunt roll vs the highest reflex among your targets, plus 1 for each target beyond the first. Dupe stunts: You can perform a number of extra stunts on your action determined by your Multiply grade.",
        damage: [],
        outcome: "",
        tier: 3,
        upgrades: [],
        table: [
            { grade: "D", Dupe: "One", Stunts: 1 },
            { grade: "C", Dupe: "Three", Stunts: 1 },
            { grade: "B", Dupe: "Several", Stunts: 2 },
            { grade: "A", Dupe: "Dozens", Stunts: 2 },
            { grade: "S", Dupe: "100s", Stunts: 3 },
        ],
        tags: ["Chain"],
    },
    {
        name: "PERCEPTION",
        power: false,
        description: "Your senses have extraordinary sensitivity and range. Each grade allows you to choose one sense; Aura vision, Infrared, Hearing, Smell, Thermal vision, Echolocation, Motion Detection, Spatial perception, Touch, EM vision, Nightvision, Sonar, Vision, Radar, Taste, X-ray. Add the Perception pool to Intelligence stunts to detect distant or inobvious details.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Wits"],
        table: [],
        tags: ["Sense Type"],
    },
    {
        name: "POCKET DIMENSION",
        power: true,
        description: "You have access to a dimension separate from our own. Add the P. Dimension pool to a Will stunt vs a target's Spirit to vacuum them into the dimension. At the end of each round captives roll Will vs. the outcome. Success means they return to this plane wherever their former captors happen to be. The pocket dimension provides life support, source unknown. However there is no water, no food, nor is there sunlight, just land and a glow bright enough to see the distant misty borders of the universe. The bearer can embellish any additional aesthetic features they wish. The size of the pocket dimension is based on the ability grade.",
        damage: [],
        outcome: "",
        tier: 3,
        upgrades: [],
        table: [
            { grade: "D", size: "A small bedroom" },
            { grade: "C", size: "The Loop Chicago" },
            { grade: "B", size: "New York City" },
            { grade: "A", size: "Illinois State" },
            { grade: "S", size: "Antarctica" }
        ],
        tags: ["Counter", "Reflect"],
    },
    {
        name: "POSSESSION",
        power: true,
        description: "The power to leave your body to possess another's. Add the Possession pool to a Will stunt vs the target's Spirit. The outcome determines how long possession lasts. The host remains aware of your presence and can stop any action that will result in their death.",
        damage: [],
        outcome: outcomeScore,
        tier: 2,
        upgrades: [],
        table: [],
        tags: ["Contagion", "On Contact"],
    },
    {
        name: "PSYCHIC",
        power: false,
        description: "Psychic represents skilled use of psychic abilities. Add the Psychic pool to Will stunts to use psychic powers.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Spirit"],
        table: [],
        tags: ["Chain"],
    },
    {
        name: "RANGED ATTACK",
        power: true,
        description: "This ability represents a ranged attack, e.g. a shuriken, acid spit, auto pistol, etc. To use Ranged Attack perform a Physical stunt. If successful, add the ability bonus to the outcome when determining damage. Subtract the total outcome from the target's health. Choose which type of damage is inflicted\u2026 heat, cold, energy, psychic, mystic, physical, radiation or toxin.",
        damage: [
            { name: "COLD", abbreviation: "(Col)" },
            { name: "ENERGY", abbreviation: "(Ene)" },
            { name: "HEAT", abbreviation: "(Hea)" },
            { name: "MYSTIC", abbreviation: "(Mys)" },
            { name: "PHYSICAL", abbreviation: "(Phy)" },
            { name: "PSYCHIC", abbreviation: "(Psy)" },
            { name: "RADIATION", abbreviation: "(Rad)" },
            { name: "SUFFOCATION", abbreviation: "(Suf)" },
            { name: "TOXIN", abbreviation: "(Tox)" },
        ],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: ["Area of Effect", "Bypass", "Contagion", "Continue", "Damage Type", "Extra Attack", "Feed", "Homing", "On Contact", "Pierce", "Pull", "Push", "Reflect"],
    },
    {
        name: "RANGED SKILL",
        power: false,
        description: "Ranged Skill represents skilled marksmanship or throwing accuracy. Add the Ranged Skill pool to Physical stunts like firing a weapon or throwing an object to hit a target at range.",
        damage: [],
        outcome: "",
        tier: 1,
        upgrades: [],
        table: [],
        tags: ["Chain", "Extra Attack", "Feed", "Reflect"],
    },
    {
        name: "RESISTANT",
        power: false,
        description: "Resistant protects you from damage. Subtract your Resistant pool from incoming damage that matches your Resistant type. If your Resistant is missing an incoming damage type you suffer full damage. Choose a damage type your Resistant affects... Damage types: physical, cold, energy, heat, mystic, psychic, radiation, suffocation, toxin and virus.",
        damage: [
            { name: "COLD", abbreviation: "(Col)" },
            { name: "ENERGY", abbreviation: "(Ene)" },
            { name: "HEAT", abbreviation: "(Hea)" },
            { name: "MYSTIC", abbreviation: "(Mys)" },
            { name: "PHYSICAL", abbreviation: "(Phy)" },
            { name: "PSYCHIC", abbreviation: "(Psy)" },
            { name: "RADIATION", abbreviation: "(Rad)" },
            { name: "SUFFOCATION", abbreviation: "(Suf)" },
            { name: "TOXIN", abbreviation: "(Tox)" },
        ],
        outcome: "",
        tier: 1,
        upgrades: [],
        table: [],
        tags: ["Absorb", "Affect Type", "Reflect"],
    },
    {
        name: "RESOLVE",
        power: false,
        description: "Resolve represents extraordinary mental fortitude. This ability allows you to resist being overwhelmed by psychics, emotions, pain, etc. During an encounter subtract your Resolve pool from the outcome of a stunt targeting your Spirit. Your Resolve pool is the number of times you can do this during an encounter.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Spirit"],
        table: [],
        tags: [],
    },
    {
        name: "RESURRECTION",
        power: true,
        description: "If killed you have a chance of returning to life. On the turn following your death, add the Resurrection pool to a Will stunt vs. your Tally. Your Tally is the number of times you have previously resurrected. This pool cannot be reduced below one die. Outcome determines how soon you resurrect and how much health you regain. Tally: Add 1 to your Tally each time you resurrect. If your stunt fails you resurrect, but your Resurrection ability has burned out and will not trigger again.",
        damage: [],
        outcome: outcomeScore,
        tier: 3,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "SCIENCE",
        power: false,
        description: "Skill and knowledge in the applied sciences. Add the Science pool to Intelligence stunts related to scientific analysis, research, development or the operation of super science apparatus.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Wits"],
        table: [],
        tags: [],
    },
    {
        name: "SHRINK",
        power: false,
        description: "You are able to shrink down to a miniscule size. While shrunken you have a bonus to your Reflex when your attackers are normal sized. Small Target: Subtract your Shrink pool from the outcome of an attack targeting your reflex. Your Shrink pool is the number of times you can use Small Target during an encounter.",
        damage: [],
        outcome: "",
        tier: 3,
        upgrades: ["Reflex"],
        table: [
            { grade: "D", height: "6\"", weight: "16 oz.", reflex: "+1" },
            { grade: "C", height: "3.75\"", weight: "6 oz.", reflex: "+1" },
            { grade: "B", height: "28mm", weight: "100 grams", reflex: "+2" },
            { grade: "A", height: "Granular", weight: "1 mote", reflex: "+2" },
            { grade: "S", height: "Microbia", weight: "Insubstantial", reflex: "+3" },
        ],
        tags: [],
    },
    {
        name: "SIPHON",
        power: true,
        description: "Through physical contact you can siphon away another's stamina to increase your power. Add the Siphon pool to a Physical stunt vs the target's reflex. Succeed and the Siphon pool is subtracted from the target's Physical stunt pools for the duration of the ability. Meanwhile you gain the use of an ability at the same grade as the Siphon pool. Choose one ability at Siphon's purchase, this choice is permanent. The amount siphoned cannot exceed your pool. The outcome determines how long before the stolen energy returns to the target. Siphon cannot be used again until the energy returns to the target or the ability it feeds is released.",
        damage: [],
        outcome: outcomeScore,
        tier: 3,
        upgrades: [],
        table: [],
        tags: ["Damage", "On Contact"],
    },
    {
        name: "SNEAK",
        power: false,
        description: "A talent for avoiding detection. To avoid detection add the Sneak pool to a Physical stunt vs. the highest Wits present. While sneaking a stunt that targets your Reflex or Wits cannot be made against you. Sneak Attack: While sneaking add your Sneak pool to a Physical stunt vs a target's Wits. Your sneaking ends after you perform an attack stunt.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Wits"],
        table: [],
        tags: ["Chain"],
    },
    {
        name: "SPEED",
        power: false,
        description: "You can move at great speed. Add the Speed pool to Physical stunts that test speed and agility. Fast: You can attack multiple targets in a single action. Add the Speed pool to a Physical stunt against the highest reflex among your targets. Success means making your target plus a number of additional targets equal to the Speed pool. The Speed pool is the number of times Fast can be used during an encounter.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Action", "Reflex"],
        table: [],
        tags: ["Counter", "Reflect"],
    },
    {
        name: "STEAL",
        power: true,
        description: "Steal abilities from others you touch. Roll Physical plus the Steal pool vs. the target ability's pool. The target ability is removed from your mark and transferred to you at its original grade. If the target ability exceeds your Steal grade they lose the ability while you gain it at a grade equal to your Steal. Your outcome determines when the stolen ability transfers back to the target. Your Steal pool is the number of abilities you can steal during an encounter.",
        damage: [],
        outcome: outcomeScore,
        tier: 3,
        upgrades: [],
        table: [],
        tags: ["Damage", "On Contact"],
    },
    {
        name: "TECHNOLOGY",
        power: false,
        description: "You're adept at repairing, altering and creating technology. Add the Technology pool to Intelligence stunts related to repair, engineering and demolitions.",
        damage: [],
        outcome: "",
        tier: 1,
        upgrades: [],
        table: [],
        tags: [],
    },
    {
        name: "TELEKINESIS",
        power: false,
        description: "The mental power to move objects remotely. Add the Telekinesis pool to Will stunts to manipulate, lift or throw objects with your mind. The heavier or more awkward the maneuver the higher the Narrator should set the difficulty. Objects must be within line of sight.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: [],
        table: [],
        tags: ["Counter", "Reflect"],
    },
    {
        name: "TELEPATHY",
        power: true,
        description: "The power to read and mentally send information to another's mind. Roll Will plus Telepathy vs Spirit to read a mind or send information to that mind. Network: You can interact with multiple minds at once. Choose the highest spirit among your targets and make your stunt roll. Success means you made your target plus one additional target for each point of your telepathy pool.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Spirit"],
        table: [],
        tags: [],
    },
    {
        name: "TELEPORT",
        power: false,
        description: "Travel instantly from one space to another. Add the Teleport pool to Physical stunts that test speed and agility. Blink: You can attack multiple targets in a single action. Add the Teleport pool to a Physical stunt against the highest reflex among your targets. Success means making your target plus a number of additional targets equal to the Teleport pool. The Teleport pool is the number of times Blink can be used during an encounter.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Action", "Reflex"],
        table: [],
        tags: ["Counter", "Reflect"],
    },
    {
        name: "WARD",
        power: false,
        description: "The ability to ward off the effects of magic. During an encounter subtract your Ward pool from the outcome of an attack targeting your Spirit. Your Ward pool is the number of times you can use Ward during an encounter.",
        damage: [],
        outcome: "",
        tier: 2,
        upgrades: ["Spirit"],
        table: [],
        tags: [],
    },
];

//TAG LIST ARRAY
const tagList = [
    {
        name: "ABSORB",
        description: "Absorbs power from an attack and channels it to another ability. Damage stopped by your defensive ability is added to the pool of the ability of your choice. This choice excludes the tagged ability and the decision is permanent. The amount absorbed cannot exceed the pool of the tagged ability, i.e. a grade B ability cannot absorb more than 3 outcome. An ability cannot be augmented beyond a pool of 5. Once the augmented ability is used the absorbed points expire.",
        addTo: ["Field", "Impervious", "Resistant"],
        abbreviation: "(Abs)"
    },
    {
        name: "AFFECT TYPE",
        description: "The ability affects all within an area. Choose the highest reflex among targets that are in proximity of one another and make your stunt roll. Success means making your target plus a number of additional targets equal to the ability pool. Example: Your Ranged Attack has a pool of 3, with the Area of Effect Tag. You’ll affect the target with the highest reflex plus three more for a total of 4 targets.",
        addTo: ["Bind", "Elasticity", "Extra Limbs", "Impair Sense", "Impair Move", "Melee Attack", "Might", "Ranged Attack"],
        abbreviation: "None"
    },
    {
        name: "BYPASS",
        description: "Allows damage to ignore fields. When a field’s grade is equal or less than the Ability’s grade, subtract the outcome from the target's health bar, not the field.",
        addTo: ["Melee Attack", "Ranged Attack"],
        abbreviation: "(Byp)"
    },
    {
        name: "CHAIN",
        description: "Put down multiple foes in a single turn. You can attack another target if the previous target was KO’d. The chain ends if you miss a target, fail to KO a target or your total KOs equal your Ability pool.",
        addTo: ["Elasticity", "Extra Limbs", "Fight", "Magic", "Melee Skill", "Multiply", "Psychic", "Ranged Skill", "Sneak", "Speed", "Teleport"],
        abbreviation: "(Cha)"
    },
    {
        name: "CONTAGION",
        description: "Physical contact with someone afflicted by the tagged ability passes its effects onto the new contact. Add to: Bind, Charm, Impair Move, Impair Sense, Mental Illusion, Mind Control, Possession, Ranged Attack, Steal. The number of additional contacts contagion can pass onto cannot exceed the tagged ability’s pool. When the tagged ability calls for an outcome use the initial outcome. This number cannot exceed the pool of the tagged ability. I.e. with bind grade B on contact can only use up to 2 of an attacker's outcome to bind the attacker. On contact does not protect the bearer from damage and the attacker’s protective abilities apply as normal.",
        addTo: ["Bind", "Charm", "Impair Move", "Impair Sense", "Mental Illusion", "Mind Control", "Possession", "Ranged Attack", "Steal"],
        abbreviation: "(Ctg)"
    },
    {
        name: "CONTINUE",
        description: "The tagged ability continues to inflict damage beyond the initial attack. Add to: Melee Attack, Ranged Attack (Can also be added to Aura, Bind and Steal; see the tag Damage) Score good or better using the tagged ability and those targeted lose one health for a number of subsequent turns equal to the tagged ability grade.",
        addTo: ["Melee Attack", "Ranged Attack"],
        abbreviation: "(Con)"
    },
    {
        name: "COUNTER",
        description: "You can counter a melee or unarmed attack to damage your attacker. Add to: Agility, Bind, Elasticity, Evade, Extra Limbs, Fight, Melee Skill, Might, Pocket Dimension, Speed, Telekinesis, Teleport. When a melee or unarmed stunt made against you scores “Good” (between 1 to 3 successes) you ignore the effects of your attacker’s ability and Tags. The attacker instead suffers the effects of your tagged ability plus one outcome. If they score bad the attacker suffers the effects of your tagged ability plus three outcome.",
        addTo: ["Agility", "Bind", "Elasticity", "Evade", "Extra Limbs", "Fight", "Melee Skill", "Might", "Pocket Dimension", "Speed", "Telekinesis", "Teleport"],
        abbreviation: "(Cou)"
    },
    {
        name: "DAMAGE",
        description: "Add a damage property to a non-attack ability. Add to: Aura, Bind, Steal. The tag adds a damage bonus to a compatible ability. Damage is equal to the pool of the tagged ability. At least one damage type must be chosen when adding this tag. Each additional damage type you apply to your ability counts as a Tag that doubles the cost of the ability. There are eight types of damage to choose from; Cold (Col), Energy (Ene), Heat (Hea), Mystic (Mys), Physical (Phy), Psychic (Psy), Radiation (Rad), Suffocation (Suf), Toxin (Tox). Characters hit with Bind or Steal also treat this ability as if they’ve been hit with a Melee or Ranged Attack. Applying any defense abilities they may possess before suffering damage from the tagged ability. Each time a character enters an Aura tagged with Damage they apply their own relevant defense abilities before suffering the Aura’s Damage.",
        addTo: ["Aura", "Bind", "Steal"],
        abbreviation: "(Dmg)"
    },
    {
        name: "DAMAGE TYPE",
        description: "Add a damage type to an attack ability. Add to: Melee Attack, Ranged Attack (Can also be added to Aura, Bind and Steal; see the tag Damage) Damage types are: Cold (Col), Energy (Ene), Heat (Hea), Mystic (Mys), Physical (Phy), Psychic (Psy), Radiation (Rad), Suffocation (Suf), Toxin (Tox).",
        addTo: ["Melee Attack", "Ranged Attack"],
        abbreviation: "(Dmg)"
    },
    {
        name: "EXTRA ATTACK",
        description: "You can attack a single target multiple times in one turn. Add to: Fight, Melee Attack or Melee Skill, Ranged Attack or Ranged Skill. You can roll an additional attack stunt on a single target during your action. The tagged pool is the number of times Extra attack can be used during an encounter.",
        addTo: ["Fight", "Melee Attack", "Melee Skill", "Ranged Attack", "Ranged Skill"],
        abbreviation: "(Exa)"
    },
    {
        name: "FEED",
        description: "Each nameless goon you put down replenishes your health. Add to: Fight, Melee Attack or Melee Skill, Ranged Attack or Ranged Skill. Each unnamed NPC serving as cannon fodder, whose health bar you reduce to KO’d, replenishes one of your lost health boxes.",
        addTo: ["Fight", "Melee Attack", "Melee Skill", "Ranged Attack", "Ranged Skill"],
        abbreviation: "(Fee)"
    },
    {
        name: "HOMING",
        description: "Your attack will follow your target until it hits or spends all attempts to do so. Add to: Elasticity, Ranged Attack. The tagged pool is the number of attempts your attack has to hit the target.",
        addTo: ["Elasticity", "Ranged Attack"],
        abbreviation: "(Hom)"
    },
    {
        name: "ON CONTACT",
        description: "Melee attacks made against you expose the attacker to the effects of the tagged ability. Add to: Bind, Charm, Copy, Impair Move, Impair Sense, Mental Illusion, Mind Control, Possession, Ranged Attack, Steal. The number of additional contacts contagion can pass onto cannot exceed the tagged ability’s pool. When the tagged ability calls for an outcome use the initial outcome. This number cannot exceed the pool of the tagged ability. I.e. with bind grade B on contact can only use up to 2 of an attacker's outcome to bind the attacker. On contact does not protect the bearer from damage and the attacker’s protective abilities apply as normal.",
        addTo: ["Bind", "Charm", "Copy", "Impair Move", "Impair Sense", "Mental Illusion", "Mind Control", "Possession", "Ranged Attack", "Steal"],
        abbreviation: "(Onc)"
    },
    {
        name: "PIERCE",
        description: "This attack pierces Resistant. Pierce allows you to ignore X* amount of the target's Resistant grade. Even when their Resistant stops all of your attack's damage types. *X equals the pool of the tagged ability.",
        addTo: ["Melee Attack", "Ranged Attack", "Aura", "Bind", "Steal"],
        abbreviation: "(Prc)"
    },
    {
        name: "PULL",
        description: "This ability pulls the target to you. When you score a Good outcome (between 1 to 3 successes) using the tagged ability the subject is pulled within reach. Their reflex is minus 1 vs. the next physical stunt you roll against them. And they will need to use a simple task to move out of reach. When you score an awesome outcome the subject is within reach and floored. Their reflex is minus 1 vs. the next physical stunt you roll against them. Getting back on their feet requires a simple task. Getting back on their feet and moving out of reach requires a full action.",
        addTo: ["Bind", "Elasticity", "Extra Limbs", "Impair Move", "Impair Sense", "Ranged Attack"],
        abbreviation: "(Pul)"
    },
    {
        name: "PUSH",
        description: "This ability pushes the target away from you. When you score Good (between 1 to 3 successes) using the tagged ability the subject is pushed outside of reach. Your Reflex is increased by 1 vs the next physical stunt they perform against you. To attempt a melee attack against you they will need to use a simple task to get back in reach. When you score an awesome outcome the subject is pushed far back and floored. Your Reflex is increased by 1 vs the next physical stunt they perform against you. Getting back on their feet requires a simple task, moving a long distance to reach you requires two simple tasks.",
        addTo: ["Elasticity", "Extra Limbs", "Fight", "Impair Move", "Impair Sense", "Melee Attack", "Ranged Attack"],
        abbreviation: "(Pus)"
    },
    {
        name: "REFLECT",
        description: "You can reflect a ranged attack back to the attacker. When a ranged stunt made against you scores less than 4 successes, Good or worse, you ignore the effects of your attacker's ability and Tags. Those effects are instead reflected back at your attacker with one outcome. If they score bad you ignore the ability's effects and reflect them back doing three outcome.",
        addTo: ["Agility", "Bind", "Elasticity", "Evade", "Extra Limbs", "Field", "Melee Attack", "Melee Skill", "Might", "Pocket Dimension", "Ranged Attack", "Ranged Skill", "Resistant", "Speed", "Telekinesis", "Teleport"],
        abbreviation: "(Rfl)"
    },
    {
        name: "SENSE TYPE",
        description: "Add a sense type to the Perception ability. Having a Sense that suits a Perception stunt can influence the Narrator when determining difficulty. Each additional sense type you apply to your Perception ability counts as a Tag that doubles the cost of the ability.",
        addTo: ["Perception"],
        abbreviation: "None",
        senseTypes: [
            { name: "Aura Vision", abbreviation: "(Auv)" },
            { name: "Infrared Hearing", abbreviation: "(Inh)" },
            { name: "Smell", abbreviation: "(Sme)" },
            { name: "Thermal Vision", abbreviation: "(Thv)" },
            { name: "Echolocation", abbreviation: "(Ech)" },
            { name: "Motion Detection", abbreviation: "(Mod)" },
            { name: "Spatial Perception", abbreviation: "(Spp)" },
            { name: "Touch", abbreviation: "(Tou)" },
            { name: "EM Vision", abbreviation: "(Emv)" },
            { name: "Night Vision", abbreviation: "(Niv)" },
            { name: "Sonar", abbreviation: "(Son)" },
            { name: "Vision", abbreviation: "(Vis)" },
            { name: "Hearing", abbreviation: "(Hrg)" },
            { name: "Radar", abbreviation: "(Rdr)" },
            { name: "Taste", abbreviation: "(Tas)" },
            { name: "X-ray", abbreviation: "(Xra)" },
        ]
    }
];
